SQLÀÇ ±¸ºÐ
DDL
(CREATE / ALTER / DROP)
DML
(INSERT / SELECT / UPDATE / DELETE) - CRUD
DCL
(GRANT/ REVOKE)

CREATE MEMBER(
    ID          VARCHAR2(50),
    PWD         VARCHAR2(50),
    NAME        VARCHAR2(50,
    GENDER      VARCHAR2(50), 
    AGE         NUMBER,
    BIRTHDAY    VARCHAR2(50),
    PHONE       VARCHAR2(50),
    REGDATE     DATE
);